name: Deploy to staging

on:
  pull_request:
    types: [labeled]

jobs:
  deploy:
    if: ${{ github.event.label.name == 'deploy' }}
    runs-on: ubuntu-latest

    steps:
      - name: Get branch names.
        id: branch_name
        uses: tj-actions/branch-names@v5
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Running on a pull request branch.
        run: |
          echo "Running on pr: ${{ steps.branch-name.outputs.current_branch }}"
          echo "$(git symbolic-ref --short HEAD)"

      - name: Merge to staging
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git fetch --unshallow
          git checkout staging
          git pull
          git merge "origin/$(git symbolic-ref --short HEAD)"
          git push
