name: Deploy to staging

on:
  pull_request:
    types: [labeled]

jobs:
  deploy:
    if: ${{ github.event.label.name == 'deploy' }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Get Branch name
        uses: nelonoel/branch-name@v1.0.1
        run: echo ${BRANCH_NAME}

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Merge to staging
        run: |
          echo ${GITHUB_REF##*/}
          echo ${{ steps.extract_branch.outputs.branch }}
