name: Deploy to staging

on:
  pull_request:
    types: [labeled]

jobs:
  deploy:
    if: ${{ github.event.label.name == 'deploy' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}

      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}
